[package]
name = "wialon-protocol"
version = "0.1.0"
authors = ["kuznetsovin <kuznetsovin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.5.0", features = ["full"] }
chrono = "0.4"